### ISSUE TITLE
Ng5 Migration

### ISSUE THREAD

**Issue by jarodsmk** [makimenko/angular-three-examples#1]
Hey @makimenko :) 
This isn't an actual issue or anything with your example, more of a query:

Was just wondering if this example of yours would work the same if a migration to Angular 5 was done?

I was using something similar, by setting the TS compiler allowJS=true, and using a seperate JS file to load the ThreeJS library, bit since the migration on my project this doesn't exactly work as it used to with Ng4 👎 

Cheers!

**Comment by jarodsmk** [comment]
I got it to work! With minimal effort, I'd like to close this but I do have one query:

Why in your example don't you have the compiler allowJS set to true?

**Comment by makimenko** [comment]
Hi @jarodsmk,

Thanks for hint.
Migrated to NG5 and allowJs settled to false.
https://github.com/makimenko/angular-three-examples/commit/9b8b2c115ac88f0d77afa7a65521d4a4398a543f

Tested -> workign well on my workstation.


Cheers!
